language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - sudo python setup.py install
  - sudo rosdep init
  - sudo rosdep update
# command to run tests
script:
  - sudo python setup.py nosetests -s
notifications:
  email: false
matrix:
  allow_failures:
    - python: "3.2"
