language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git-buildpackage
  - sudo pip install empy
  - sudo pip install python-dateutil
  - sudo python setup.py develop
  - sudo rosdep init
  - sudo rosdep update
# command to run tests
script:
  - sudo python setup.py nosetests -s
notifications:
  email: false
