language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git-buildpackage
  - python setup.py build
  - sudo pip install -r bloom.egg-info/requires.txt
  - sudo rosdep init
  - rosdep update
# command to run tests
script:
  - sudo python setup.py nosetests -s
notifications:
  email: false
