language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - sudo pip install empy
  - sudo apt-get install git-buildpackage
  - sudo python setup.py develop
# command to run tests
script:
  - sudo python setup.py nosetests
