language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - GIT=v1.7.9.5
# command to install dependencies
install:
  - pip install empy PyYAML argparse rosdep rospkg vcstools catkin-pkg python-dateutil distribute
  - pip install nose coverage
  - sudo pip install rosdep
  - sudo rosdep init
  - rosdep update
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test User"
# command to run tests
script:
  - BLOOM_VERBOSE=1 python setup.py nosetests -s --tests test
notifications:
  email: false
matrix:
  allow_failures:
    - python: "3.2"
